spring:
  boot:
    admin:
      client:
        url: http://localhost:8081
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:springboot-demo
    username: sa
    password:
  h2:
    console:
      enable: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

#Monitoramento
management:
  security:
    enabled: false
  endpoint:
    health:
      show-details: always
    web:
      exposure:
        include: "*"
#info:
#  app:
#    name: ^project.name^
#    description: ^project.description^
#    version: ^project.version^
#    encoding: ^project.build.sourceEncoding^
#    java:
#      version: ^java.version^
#Monitoramento